language: node_js

sudo: required

node_js: 10.3.0

cache:
  direactories:
    - node_modules

install:
  - yarn

script:
  - yarn run build

# https://docs.travis-ci.com/user/deployment/pages/
# skip-cleanup 必须为 true，否则 CI 在 build 期间将删除所有准备上传的文件
deploy:
  provider: pages
  skip-cleanup: true
  # 在 CI 后台配置 GITHUB_TOKEN 变量为 personal access token
  github-token: $GITHUB_TOKEN
  local-dir: docs/.vuepress/dist
  on:
    branch: master

# https://zhuanlan.zhihu.com/p/36390666
# 使用 shell 部署
# language: node_js
# sudo: required
# node_js:
#   - 10.3.0
# cache:
#   directories:
#     - node_modules
# script:
#     - ./deploy.sh 'deploy: site by CI'
# branch: master